version: '3.7'

services:
    backend:
      image: huerta-iot/backend:1.0
      environment:
        MQTT_URL: mqtt://emqx:1883 
        DB_URL: http://admin:admin@couchdb:5984
      ports: 
      - 3001:3001
      networks:
      - huerta_iot_net

networks:
  huerta_iot_net:
    external: true