version: '3.9'

services:
    couchdb:
      image: apache/couchdb:3
      hostname: couchdb.{{.Task.Slot}}.iot
      environment:
        COUCHDB_USER: "admin"
        COUCHDB_PASSWORD: -pbkdf2-ec6f84b04adce620e9d10512c8a5af9c4fe8379f,8a3bfe04b1f4294d89d9e9d250fce77a,10
        COUCHDB_SECRET: 46d689495ca02e8c35c3a3f683000ef1
        NODENAME: "couchdb.{{.Task.Slot}}.iot"
        ERL_FLAGS: "-setcookie a20b37d83ef18efce400b3ace400036e"
      volumes:
      - couchdb-data:/opt/couchdb/data
      ports:
      - 5984:5984
      - 4369:4369
      deploy:
        placement:
          max_replicas_per_node: 1
      networks:
      - huerta_iot_net

networks:
  huerta_iot_net:
    external: true

volumes:
  couchdb-data:
    name: "couchdb-.{{.Task.Slot}}-vol"

# manejo del cluster
# https://docs.couchdb.org/en/stable/cluster/nodes.html

# curl -X GET "http://<setup-coordination-node>:5984/_membership" --user admin-user

# agregar
# curl -X PUT "http://<setup-coordination-node>/_node/_local/_nodes/node2@yyy.yyy.yyy.yyy" -d {}
# Verificar instalacion:
# curl http://admin:password@<setup-coordination-node>:5984/_cluster_setup

# Ver miembros:
# curl http://admin:password@<setup-coordination-node>:5984/_membership

# https://stackoverflow.com/questions/71779828/how-to-limit-container-running-on-different-node-use-docker-stack-deploy
# https://stackoverflow.com/questions/48853473/pros-and-cons-of-running-all-docker-swarm-nodes-as-managers