version: '3.7'

services:
    # front-end (usando svelte)
    frontend:
      image: cbiale/huerta-iot:frontend-1.0
      ports: 
      - 5001:5001
      networks:
      - huerta_iot_net
  
networks:
  huerta_iot_net:
    external: true