version: '3.7'

services:
    # back-end (usando fastify)
    backend:
      image: huerta-iot/backend:1.0
      ports: 
      - 3001:3001
      networks:
      - huerta_iot_net

networks:
  huerta_iot_net:
    external: true