version: '3.9'

services:
  emqx:
    image: emqx/emqx:5.0.8
    environment:
      EMQX_NODE__COOKIE: emqx-huerta-iot
      EMQX_DASHBOARD__DEFAULT_PASSWORD: 1978-huerta-iot
      EMQX_CLUSTER__DISCOVERY_STRATEGY: manual
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    deploy:
      placement:
        max_replicas_per_node: 1
    networks:
      - huerta_iot_net

networks:
  huerta_iot_net:
    external: true
