version: '3.7'

services:
    # front-end (usando svelte)
    frontend:
      image: huerta-iot/frontend:1.0
      ports: 
      - 5000:5000
      environment:
        IP_HOST: localhost
      networks:
      - huerta_iot_net
  
networks:
  huerta_iot_net:
    external: true