version: '3.7'

services:
  emqx:
    image: emqx/emqx:4.2.11
      environment:
        EMQ_NODE_NAME: "{{.Service.Name}}.{{.Task.Slot}}"
        EMQ_NODE_COOKIE: emqx-huerta-iot
    ports:
      - 1883:1883
      - 8081:8081
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    networks:
      - huerta_iot_net

networks:
  huerta_iot_net:
    external: true
