# fly.toml file generated for huerta-mqtt on 2021-02-01T12:48:03-03:00

app = "huerta-mqtt"

kill_signal = "SIGINT"
kill_timeout = 5


[[services]]
  internal_port = 1883
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 200
    soft_limit = 20

  [[services.ports]]
    handlers = [ ]
    port = "10000"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "10s"
    port = "8080"
    restart_limit = 5
    timeout = "2s"

[[mounts]]
source="mosquitto_data"
destination="/mosquitto/data"

[experimental]
  private_network=true

